### ISSUE TITLE
Duplicated code logic in source?

### ISSUE THREAD

**Issue by DantaAlighieri** [4AI/TDEER#4]
I guess whether there is some duplicated logic in **Utils.py** this file：

please see the picture.
entity = self.decode_entity(text, mapping, head, tail)
on the top of this picture, sub entity is decoded, then save in subjects.
when iterating the subjects list, sub entity is decoded twice again.

![image](https://user-images.githubusercontent.com/56987319/156173884-a29c87b9-5e95-46e8-a39f-109e3273b6ba.png)

**Comment by SeanLee97** [comment]
Oh, it is really duplicated code, I will remedy this later.  Many thanks to @DantaAlighieri
